name: Run tests
on:
  push:
    branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        environment: 
            name: latest commit (tests succeeded)
            url: https://github.com/JokeNetwork/vegancheck-api-wrapper

        steps:
          - uses: actions/checkout@v3

          - uses: actions/setup-node@v3
            with:
              node-version: "19"

          - run: npm ci
          - run: npm test